server:
  port: 9090
  servlet:
    context-path: /api
spring:
  cloud:
    nacos:
      discovery:
        namespace: 3cf0a2ce-0e41-4b86-9cb0-a5ff821d3051   #fat环境命名空间
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/xm_training?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    database: 0
    host: redis
    port: 6379
    password: 123456
      # 密码
      #配置jedis客户端，这里也可以jedis替换为lettuce客户端，下级配置都一样
    jedis:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 3000
  cache:
    type: redis # 缓存类型
      # redis:    当自定义ChacheManager时，就这里的配置不需要配置，配置了也不起作用
      #   use-key-prefix: true  #缓存数据key是否使用前缀，默认是true
      #  key-prefix: "demo:"   #缓存数据key的前缀，在上面的配置为true时有效，
      #  time-to-live: 60000  #redis中缓存超时的时间，默认60000ms
      #  cache-null-values: false  #是否缓存null数据，默认是false
    cache-names: serverInfo
cache:
  ttl: '{"serverInfo":60,"dept":30}'  #自定义某些缓存空间的过期时间
snowflake:
  dataCenterId: 1
  workerId: 2
# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springcloud.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
