server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/linux_utilization?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
    database: 0
  cache:
    type: redis
    redis:
      time-to-live: 1800000 #设置缓存过期时间

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

utilization-server:
  config:
      file-path: config/config.json
  local:
     file-path: C:/Users/Lenovo/Desktop/local_file.log
  log-storage: mysql