spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123
    url: jdbc:mysql://localhost:3306/record?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  data:
    redis:
      host: localhost
      port: 6379
      password: abc123
      database: 0

mybatis-plus:
  #mapper配置文件
  mapper-locations: "classpath:/mapper/**/*.xml"
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
server:
  port: 18080

