server:
  port: 8888
spring:
  datasource:
    username: root
    password: 083200sml.S
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.68.247:3306/cpu_data?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false

  redis:
    database: 0
    host: 117.72.68.247
    port: 6379
    password: 083200sml.S
    # 连接超时时间
    timeout: 2s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
