server:
  port: 8080

spring:
  application:
    name: collector-service
  cloud:
    nacos:
      config:
        server-addr: 192.168.80.128:8848

  redis:
    host: 192.168.80.128
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s