#数据源
spring:
  datasource:
    url: jdbc:mysql://172.27.72.128:3306/metrics?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#配置redis
  data:
    redis:
      host: 172.27.72.128
      port: 6379

#日志
logging:
  level:
    root: info

#配置mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml