server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cpu_utilization_service?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
    database: 0
  cache:
    type: redis
    redis:
      time-to-live: 1800000 #设置缓存过期时间
#  cloud:
#    nacos:
#      server-addr: nacos:8848 # nacos地址

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS