version: '3.8'

services:
   mysql:
      image: mysql:8.0
      container_name: mysql02
      hostname: asc_mcp
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: task
      ports:
        - "3306:3306"
   collector:
      build:
        context: ./collector
        dockerfile: Dockerfile
      restart: always
      hostname: asc_mcp
      depends_on:
         - server
      
   server:
      build:
        context: ./server
        dockerfile: Dockerfile
      hostname: asc_mcp
      volumes:
        - ./server/localLogs:/logs
      ports:
        - "8080:8080"
      restart: always
      
