spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cpu_utilization_service?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lhf2003
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: cpu-service

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.org.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

server:
  port: 8081
dubbo:
  application:
    name: cpu-service
  protocol:
    name: dubbo
    port: -1 # 端口设置为-1 是让dubbo自动在[20880, 65535]之间找一个可用的端口
  registry:
    address: nacos://localhost:8848 # 配置nacos服务的IP地址及端口
    parameters:
      register-consumer-url: true # 注册接口级消费者
  consumer:
    timeout: 50000